# Generated by Django 6.1 on 2026-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteEndemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_notificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('data_notificacao', models.DateField(blank=True, null=True)),
                ('data_pri_sintoma', models.DateField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadDBF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='dbfs/')),
                ('data_upload', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
