# Generated by Django 6.1 on 2026-08-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pacienteendemia_id_agravo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteendemia',
            name='hospital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacienteendemia',
            name='id_unidade',
            field=models.TextField(blank=True, null=True),
        ),
    ]
