# Generated by Django 6.1 on 2026-08-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pacienteendemia_hospital_pacienteendemia_id_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteendemia',
            name='cs_sexo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
