# Generated by Django 6.1 on 2026-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pacienteendemia_classi_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteendemia',
            name='classi_fin',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
