# Generated by Django 6.1 on 2026-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pacienteendemia_classi_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteendemia',
            name='classi_fin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
