# Generated by Django 6.1 on 2026-09-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pacienteendemia_classi_fin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PacienteEndemia',
            new_name='EndemiasDengue',
        ),
    ]
