# Generated by Django 6.1 on 2026-09-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_pacienteendemia_endemiasdengue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndemiasDengue',
            new_name='PacienteDengue',
        ),
    ]
