# Generated by Django 6.1 on 2026-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pacientetuberculose'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteSifilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mu_notific', models.TextField(blank=True, null=True)),
                ('un_saude', models.TextField(blank=True, null=True)),
                ('mu_residen', models.TextField(blank=True, null=True)),
                ('nu_notific', models.TextField(blank=True, null=True)),
                ('dt_notific', models.DateField(blank=True, null=True)),
                ('id_agravo', models.TextField(blank=True, null=True)),
                ('nm_pacient', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
