# Generated by Django 6.1 on 2026-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pacientesifilis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientesifilis',
            name='nm_ubs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
