# Generated by Django 6.1 on 2026-08-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteendemia',
            name='id_agravo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
