# Generated by Django 6.1 on 2026-08-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pacienteendemia_cs_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteendemia',
            name='classi_fin',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
